// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package webscraper

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebscraperServiceClient is the client API for WebscraperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebscraperServiceClient interface {
}

type webscraperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebscraperServiceClient(cc grpc.ClientConnInterface) WebscraperServiceClient {
	return &webscraperServiceClient{cc}
}

// WebscraperServiceServer is the server API for WebscraperService service.
// All implementations must embed UnimplementedWebscraperServiceServer
// for forward compatibility
type WebscraperServiceServer interface {
	mustEmbedUnimplementedWebscraperServiceServer()
}

// UnimplementedWebscraperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWebscraperServiceServer struct {
}

func (UnimplementedWebscraperServiceServer) mustEmbedUnimplementedWebscraperServiceServer() {}

// UnsafeWebscraperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebscraperServiceServer will
// result in compilation errors.
type UnsafeWebscraperServiceServer interface {
	mustEmbedUnimplementedWebscraperServiceServer()
}

func RegisterWebscraperServiceServer(s grpc.ServiceRegistrar, srv WebscraperServiceServer) {
	s.RegisterService(&WebscraperService_ServiceDesc, srv)
}

// WebscraperService_ServiceDesc is the grpc.ServiceDesc for WebscraperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebscraperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webscraper.webscraperService",
	HandlerType: (*WebscraperServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/playerstuff.proto",
}
